name: CI
env:
  BUNDLE_PATH: vendor/bundle

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ruby-setup
      - run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ruby-setup
      - run: bundle exec rspec
